#34
ayieru/Unity_GameAward pull request #45
Opened 2022-05-02 13:48 UTC by SatouRiku

鎖実装完了

★配置方法と数値設定★

①prefabにあるChainObjectを配置

②プレイヤーのインスペクター画面に移動。
ReleasePowerは50くらいに設定

③プレイヤーの子オブジェクトのカメラのインスペクター画面に移動。
CameraLockRotateというスクリプトが入っているか確認してください。入ってない場合は入れてOKです。
PlayerObjにはプレイヤーを入れてください。

④ChainObjectのインスペクター画面に移動
RoundTripTime(往復時間)は10←大きくするほど遅くなる
それ以外はそのままでもOK(お好みで適当にいじっても大丈夫です！)

⑤続いてChainObjectのインスペクター画面。
ArrivalPointにはChainObjectの子オブジェクトであるArrivalPointを入れる

鎖に触れると振り子のように動き出します。この間プレイヤーはスペースキーのみ入力可能です。着地したらまた普通に操作ができます。

2022-05-03 23:54 UTC, wonkle07 requested changes
・鎖の動作は確認できました！
・PlayerについてるカメラとChainObjectについてるスクリプトが消えてたので、修正した方が良いかもです。
・Player.csでコンフリクトが起きてます。（勝手に直すのは怖いので、放置しておきます…ごめんね）

2022-05-04 01:05 UTC, wonkle07 reviewed
PlayerのカメラとChainObjectのprefabについてるスクリプトが消失したままになってるから、付け直した方が良いかも。

2022-05-04 01:06 UTC, wonkle07 approved these changes

2022-05-10 01:49 UTC, ayieru approved these changes
修正と確認終わりました。

2022-05-10 01:50 UTC, merged